### ISSUE TITLE
Update TimeseriesSelectView

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/geomag-plots#100]
Integrate ObservatorySelectView and ChannelSelectView.
When an observatory is selected update config model to have observatory and all channels.
When a channel is selected update config model to have channel and all observatories.

**Comment by hasimpson-usgs** [comment]
Should get channels collection and observatory collection from application, and pass through to ObservatorySelectView and ChannelSelectView.

**Comment by hasimpson-usgs** [comment]
When updating config model set channel and observatory properties as arrays of ID's in corresponding collections. 
Deselect in opposite collection.

**Comment by emartinez-usgs** [comment]
Do not set config observatories to null when an element is selected. Instead, set config observatories to an array of all observatory ids when an element is selected.

The same applies vice-versa.
