### ISSUE TITLE
Update TimeseriesView to handle empty data and time.

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/geomag-plots#101]

**Comment by jdbrown-USGS** [comment]
When no data is available for a graph it is greyed out. Hovering over the graph shows a tool tip with the title "No Data" and and start and end time of 0. Should this be shown in a different way?

**Comment by jmfee-usgs** [comment]
Does it always say start/end of 0, or only until data loads?

**Comment by jdbrown-USGS** [comment]
No changes needed
