### ISSUE TITLE
Update TimeseriesView to use channel and observatory metadata.

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/geomag-plots#103]
From Timeseries model object.

**Comment by emartinez-usgs** [comment]
Not sure what to do for this. The `timeseries.metadata` appears to be null. The code currently seems to already look at the "id" and "units" properties of the `timeseries.element` and `timeseries.observatory` so is this already done or does `timeseries.metadata` need to be populated and used?

**Comment by jmfee-usgs** [comment]
That specific portion is complete, however the range plotting on the y axis should also be updated to use element units.

**Comment by emartinez-usgs** [comment]
Still not entirely sure what is needed for this ticket. I added units to the y-axis tick values and I'm using the `timeseries.element.properties.units` to do so. Is this complete?
