### ISSUE TITLE
Remove channel references

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/geomag-plots#115]
Channels are now referred to "elements". To avoid confusion...

- Delete references to channel that are already replaced by elements.
- Change variables etc... to reference "element" or "elements" (as appropriate) rather than "channel" or "channels".

**Comment by jmfee-usgs** [comment]
Timeseries no longer have a "metadata" model property (or rather don't always have), but instead have "element" and "observatory" model properties that are features from the elements and observatories collections.

**Comment by jmfee-usgs** [comment]
rebase
