### ISSUE TITLE
Scale View selection does not hide offcanvas

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/geomag-plots#134]
When any of the TimeseriesSelectView options are selected offcanvas should be hidden. It looks like this works for all options other than "Scale View".

**Comment by jdbrown-USGS** [comment]
https://github.com/usgs/geomag-plots/pull/138

**Comment by jmfee-usgs** [comment]
Remove this from ScaleView, it already does its job of updating the plotModel.  Instead, in TimeseriesApp, bind plot model changes to onConfigChange which already hides the offcanvas.
