### ISSUE TITLE
Update observatories.json in geomag-edge-ws

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-plots#139]
Add "CMT" observatory, is the ObsRio version of College observatory.

Add " (ObsRIO)" to end of CMT, BRT, DHT observatory descriptions (Similar to TST).

**Comment by jmfee-usgs** [comment]
Use "Index" abbreviation for USGS observatory

**Comment by jmfee-usgs** [comment]
Also update elements.json name for "Z" element, to "Observatory Vertical Component"

**Comment by jmfee-usgs** [comment]
Also update "T-P" and "Proton Temperature" to "T-T" and "Total Field Temperature"

**Comment by jmfee-usgs** [comment]
Also update elements.json name for "D" element to "Declination (deci-arcminute)"

**Comment by ehunter-usgs** [comment]
https://github.com/usgs/geomag-edge-ws/pull/15
