### ISSUE TITLE
Dst page names labeled incorrectly

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-plots#153]
I just noticed that you have it labeled as "DST".  The correct name of the Index is "Dst".  Can you please fix this immediately on the Plots page, where the link to "DST Index" is, and also on the main page heading at the top, where it says "Disturbance Storm Time (DST) Index".  And yes, it makes a big difference.

**Comment by jmfee-usgs** [comment]
- Should I keep Storm and Time capitalized in non-abbreviated version?
- Are "DstH", "Dst3", and "Dst4" the desired plot labels?
- Are there other changes I should incorporate at the same time?

**Comment by cafinn-usgs** [comment]
- Should I keep Storm and Time capitalized in non-abbreviated version?
   *Yes*.
   - Are "DstH", "Dst3", and "Dst4" the desired plot labels? *Not exactly.
   I would prefer:  *
      - *Dst-1hr (instead of DstH)*
      - *Dst-1min (instead of Dst4)*
      - *Dst3-USGS (instead of Dst3)*
   - Are there other changes I should incorporate at the same time? *Let's
   double-check my changes and any others with Josh.*
