### ISSUE TITLE
Add channel units to metadata

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#30]
Some indices like K are unit-less (represent as null), set in Timeseries metadata.
Update timeseries view metadata display accordingly.

**Comment by erigler** [comment]
Just a reminder that declination has units of minutes (I believe, maybe it's degrees). I'm sure there will be additional examples as we expand our selection of data types.

**Comment by hasimpson-usgs** [comment]
Handled by channel list.
