### ISSUE TITLE
Add BDT channel

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#32]
We need BDT included among the listed channels. It is available in Edge.

**Comment by emcwhirter-usgs** [comment]
This is BDT only, not the other test observatory channels, because BDT is the last PCDCP system that is not currently being shown. (It is technically Boulder Secondary, not Boulder Test).

**Comment by ttwhite-USGS** [comment]
Add to the Public and Dev web page.

**Comment by hasimpson-usgs** [comment]
Will be taken care of by observatory list.
