### ISSUE TITLE
dB/dt diagnostic channel

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#33]
We probably want this channel in Edge first instead of computing it on the fly.

dB/dt is a diagnostic channel for assessing spikes, bin changes and field behavior.

dB/dt is defined as the difference in the data from one point to the next, so:
dB/dt for minute 0 = minute 0 - minute 1
dB/dt for minute 1 = minute 1 - minute 2
dB/dt for minute 2 = minute 2 - minute 3

**Comment by cafinn-usgs** [comment]
Got a request from one of our users, wanting to know when we were going to implement this:

---------- Forwarded message ----------
From: Greenhill, John <JOHN.GREENHILL@hq.doe.gov>
Date: Fri, Oct 23, 2015 at 1:08 PM
Subject: Newport Magnetometer
To: "cafinn@usgs.gov" <cafinn@usgs.gov>

Carol,

When is the USGS going to display the dB/dt plots?

**Comment by ttwhite-USGS** [comment]
H(t+1)-H(t), same for E, Z and F

**Comment by hasimpson-usgs** [comment]
This will be implemented as an algorithm.  And made available once data is in the edge.

**Comment by cafinn-usgs** [comment]
1) So perhaps I don't understand the process, but have you added a new issue somewhere else to have this implemented as an algorithm? Otherwise it will be lost.

2) Don't we still need to leave this open so that once the data exist in Edge someone will modify the plots to display this data channel?

**Comment by hasimpson-usgs** [comment]
1) Will do.
2) Channels will be added to this interface, by adding them to the webservice list.
