### ISSUE TITLE
Copy of /plots for ObsRIO data

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#34]
This page would be used primarily to QC and teach others to QC ObsRIO data. Channels will include BRT, DHT, CMT and TST. This should be an exact copy of the current /plots page, but with ObsRIO data only.

Tim would like this by the end of July (didn't happen). The primary users will be Tim and Schlumberger for now. In the long run (more than a year from now), the ObsRIO data will be the primary source of data, which would make this new page obsolete.

**Comment by cafinn-usgs** [comment]
This needs to be closed, since it was implemented on http://ehpd-geomag.cr.usgs.gov/plots/.
