### ISSUE TITLE
More options for entering custom times

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#40]
It was requested that there be more options for entering custom times, possibly a calendar or drop down.

**Comment by erigler** [comment]
Maybe this needs a new feature request, but I notice that if I have two dates specified (begin/end), then I change the end date to something relatively farther into the future with the intent of changing the begin date by a similar amount, the plots update, potentially pulling way more data than I actually want. I get around this by remembering to change the dates in an order that puts begin after end, but this is less than ideal.

I recommend that the plots do NOT update unless/until the user clicks "update", which is what I expect with such a button anyway.

**Comment by hasimpson-usgs** [comment]
This will be addressed by letting the user pan or zoom out to an earlier time.
