### ISSUE TITLE
Compare observatories within latitude bands

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#42]
Users would like a way to quickly check the general activity across observatories. They would like to do this by using a fixed scale system instead of auto-scaling everything.

Each of these lists is in order:
 - High Latitude - BRW, CMO, SIT, SHU, NEW
 - Mid Latitude - NEW, BOU, FRD, FRN, BSL
 - Low Latitude - GUA, HON, TUC, BSL, SJG

To facilitate easy comparison of activity among all stations, users would like to see a fixed scale of 1,000nT for High Latitudes, 200nT for Mid Latitudes and 100nT for Low Latitudes.

**Comment by erigler** [comment]
Maybe another feature request is required, but I would advocate for user-defined scaling if that is possible. This is definitely a "would be nice" feature, and should receive corresponding priority.

**Comment by cafinn-usgs** [comment]
Clarification on the high/mid/low latitude scale values above, which is not exactly correct.  Jeff Love later clarified as follows:

The scaling used for the different latitude groups changes, depending on activity level, but it is always the same within each latitude group and always in sensible units of scaling, so 50, 100, 200, etc. Point being, we need to be able to compare activity levels among observatories (which autoscaling does not facilitate) and, at the same time, accommodate different activity levels at different latitudes.

**Comment by cafinn-usgs** [comment]
This might be solved by adding bookmark functionality and configurable displays.
