### ISSUE TITLE
Searchable bin change logs

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#43]
Observatory bin change information needs a search/analysis interface. This interface allows the user to analyze bin changes for H, E and Z based on voltages, bins and nT values.

From Jeremy:
> displaying the "bin" timeseries, and allow user to zoom in on all timeseries to see what happened.

This is necessary for replacing WebDisplay.

**Comment by emcwhirter-usgs** [comment]
As discussed in a prior meeting, all data about the data that can be generated, should be generated on the fly. So, what we really need here is to start storing bins and voltages in Edge, then add an interface that can generate a bin change display/log based on start and end times.

**Comment by hasimpson-usgs** [comment]
Will display the bin channel for now.
