### ISSUE TITLE
Link to geomag webservice.

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#46]
Users would like to be able to view Geomag data in table view in addition to plot view. I'm not sure how useful this will be when users are able to hover over data to see actual values, but we can readdress this after real-time geomag data is in use.

This is supposedly necessary for replacing WebDisplay.

**Comment by cafinn-usgs** [comment]
This might also be incorporated into the larger observatory monitoring system effort somehow.

**Comment by jmfee-usgs** [comment]
This may also be supported by the updated webservice with IAGA2002 output support (which is essentially a table view of data).

**Comment by hasimpson-usgs** [comment]
Link to webservice in navigation for users to download raw data.

**Comment by hasimpson-usgs** [comment]
geomag.usgs.gov/ws/edge/
