### ISSUE TITLE
Static time series plot baselines

### ISSUE THREAD

**Issue by erigler-usgs** [usgs/geomag-plots#50]
It is debatable whether a floating baseline is desirable for geomagnetic time series plots, but for certain variables, most notably Dst, it really only makes sense to plot values relative to zero (similar for indices AU and AL, which fall out of AE calculations, but these are not yet operational).

This is regardless of what the range of Dst values are over a plot window, so it's not really a autoscaling-related feature request. Perhaps, until user-defined scales are implemented, we can set something up that forces certain channels to use a static baseline.

**Comment by emcwhirter-usgs** [comment]
This may be taken care of by #63, re-evaluate later.
