### ISSUE TITLE
More significant digits on data ranges

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#52]
Users would like to see the 3 most significant digits on the plot data ranges instead of just a 0.1nT resolution.

**Comment by jmfee-usgs** [comment]
We show all available significant digits, and data are only reported to 0.01nT resolution.

**Comment by cafinn-usgs** [comment]
What we were asking for is that we shouldn't round the subtraction of the values on the y-axis...so a high point of 9288.61 minus a low point of 8769.24 should show a range of 519.37 instead of 519.4 nT like it does right now.
