### ISSUE TITLE
Re-design interface to accommodate new data

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#61]
Each observatory now has quite a few channels (9+), and we will soon be adding 4 temperature channels and 2 voltage channels as well as location codes and housekeeping voltage and bin channels (6 more). This is going to get large and cluttered with the current interface. A redesign will be needed.

**Comment by emcwhirter-usgs** [comment]
This might be best handled by providing a customization interface for the users with some reasonable defaults (i.e. let the user pick which channels they want to see).

**Comment by hasimpson-usgs** [comment]
This will be addressed by making the observatory and channel lists load from the webservice.
