### ISSUE TITLE
problem plotting 20+ days of D channel data

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-plots#65]
Using http://ehpd-geomag.cr.usgs.gov/plots/, and Mozilla firefox or Google Chrome,
I was trying to view the month of Dec 2015's magnetic data with Geomag Plots, when I discovered some issues by trial and error:
- I can display 20 days of D channel data (say 12/1/15 00:00:00 - 12/20/15 00:00:00), but not 21.  Screen goes blank and never fills in.
- Same problem with 21 days of Delta-F, X, and Y data.
- All other channels (H, E, Z, F, Dist) plot fine.
- I have looked at individual days of D, X, Y, and Delta-F channel data past 12/20, and the data exist for 12/21 and beyond, but often (but not always!) do not display if more than 24 hrs of data is requested in 'custom'.
- I suspect this is related to memory, because once I've "hit the limit" on displaying data, I am unable to re-display similar time frames from even the 'good' channels until I go back to a smaller time frame (like real-time, or 1 day, or 10 days) and then increase the time frame from there.

This is a real problem if we are not able to view custom time frames of data consistently from ALL of our channels.

**Comment by jmfee-usgs** [comment]
It's hard to say whether this is interface related, or web service related.  We're planning to make improvements to both, and will factor this requirement into planning.

**Comment by hasimpson-usgs** [comment]
This will be addressed by loading data incrementally, and making hourly data available in the edge.

**Comment by cafinn-usgs** [comment]
I'm not crazy about the idea of closing an issue until we know that it's actually been resolved.
