### ISSUE TITLE
Update List of Channels.

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/geomag-plots#78]

**Comment by hasimpson-usgs** [comment]
Here's a spreadsheet with all known/planned geomag channels.  This is too comprehensive of a list for geomag plots.  

https://docs.google.com/spreadsheets/d/1Bxr_x0VyKI3BDeilB1dd8qkuK9wGQd97cKuxA5GkMn4/edit#gid=1790460847

**Comment by emartinez-usgs** [comment]
This spreadsheet seems incomplete.

- The following channels are not supported by the web service: A, B, V, S
- The spreadsheet makes no mention of  "Dst" or "Dist"
- Are there any other channels that need to be added/removed from this list?

- How should we handle "G" (DeltaF). Can we just display "G", or should we implement some sort of channel mapping between display and id?

**Comment by jmfee-usgs** [comment]
we'll need to discuss this more.

**Comment by hasimpson-usgs** [comment]
Add elements.json file to geomag-edge-ws project.
src/htdocs/elements.json

Like a geojson feature collection.  Look at the observatories.json file as an example.

All units are nT except where noted.

H,  Observatory North Component
E,  Observatory East Component
Z,  Vertical Magnitude
F,  Total Field Magnitude
X,  Geographic North Magnitude
Y, Geographic East Magnitude
D, Declination (10ths of minutes)
G: DeltaF, 
UK1: Electronics Temp (degrees C)
UK2: Fluxgate Temp (degrees C)
UK3: Proton Temp (degrees C)
UK4: Outside Temp (degrees C)
MSQ: Solar Quiet 
MSV: Solar Variation
MSD: Disturbance
'''
{
  id: "H",
  properties: {
    sampling_periods: [1, 60],
    element: "H",
    units: "nT",
    name:"Observatory North Component"
  }
}
'''

**Comment by hasimpson-usgs** [comment]
Extra points if you work in a flux copacitor that no one finds.

**Comment by jmfee-usgs** [comment]
Deployed 2016-06-03
https://github.com/usgs/geomag-edge-ws/releases/tag/v0.1.2
