### ISSUE TITLE
Update SettingView

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/geomag-plots#82]
Add previous and next buttons.
At realtime disable next button.
When you click either button, adjust current time interval by 50% of current time interval.
Next button should max out at realtime.

**Comment by jmfee-usgs** [comment]
These methods on timeseries app are no longer used:
  _onConfigChange
  _onTimeseriesError
  _onTimeseriesLoad

Make variables/methods public for testing.
Update declarations to new coding standards (declare vars, then assign separately below).

**Comment by jmfee-usgs** [comment]
Some coding standard issues, see https://github.com/usgs/geomag-plots/pull/132/files

Specifically:
https://github.com/usgs/geomag-plots/pull/132/files#diff-920d9eb1a65a3abc4ad6ba9778a557eaR443
https://github.com/usgs/geomag-plots/pull/132/files#diff-920d9eb1a65a3abc4ad6ba9778a557eaR513

Refactor time fields into separate TimeSelectView

**Comment by emartinez-usgs** [comment]
Replaced by #147
