### ISSUE TITLE
Create TimeseriesManager

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-plots#92]
The new web service only supports data from a single observatory in each request.  The application needs to be updated to load data for each timeseries in a separate web service request.

**Comment by hasimpson-usgs** [comment]
When channels or observatories change on the config, update timeseries collection with timeseries model objects for each selected channel/observatory combination,  and remove any others, and begin fetching data.
When starttime or endtime change on the config, begin fetching data.
When fetching data abort any previous data fetches first.

**Comment by hasimpson-usgs** [comment]
config channel and observatory properties will be arrays of ID's for objects in the corresponding collections.

**Comment by jmfee-usgs** [comment]
If a request fails, set an "error" property to an error message to be displayed on the corresponding Timeseries object.
