### ISSUE TITLE
Mime type for json format on webservice.

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/geomag-plots#96]
geomag-edge-ws
https://github.com/usgs/geomag-edge-ws/blob/master/src/lib/classes/JsonOutputFormat.class.php
Should be serving an appliction/json Content-type header.

**Comment by hasimpson-usgs** [comment]
In TimeseriesFactory, remove if statement that parses strings into json objects.

**Comment by jdbrown-USGS** [comment]
- Added header https://github.com/usgs/geomag-edge-ws/pull/11
