### ISSUE TITLE
Create Channel SelectView

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/geomag-plots#98]

**Comment by hasimpson-usgs** [comment]
Keep compact format.  Use Name as title text, and ID as display text.

**Comment by hasimpson-usgs** [comment]
Trigger select on channel collection. 
And handle deselect.

**Comment by jmfee-usgs** [comment]
this should probably be called ElementSelectView

**Comment by emartinez-usgs** [comment]
Depends on https://github.com/usgs/hazdev-webutils/pull/78

**Comment by emartinez-usgs** [comment]
Creating `CompactSelectView` as an abstraction for this as well as #99.
